name: 'json_dynamic_widget_extension'
description: 'A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.'
repository: 'https://github.com/peiffer-innovations/json_dynamic_widget/tree/main/extension'
version: '7.0.5+1'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  devtools_app_shared: ^0.0.6
  devtools_extensions: ^0.0.9
  json_dynamic_widget: any

dev_dependencies:
  flutter_lints: '^3.0.1'
  flutter_test:
    sdk: 'flutter'

dependency_overrides:
  json_dynamic_widget:
    path: '../json_dynamic_widget'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
